{
  "formatVersion": "1.1",
  "component": {
    "group": "com.adambots.lib",
    "module": "AdambotsLib-java",
    "version": "2026.3.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AdambotsLib-java-2026.3.17.jar",
          "url": "AdambotsLib-java-2026.3.17.jar",
          "size": 26848072,
          "sha512": "ed3841f284112ea3e344847a240b855585f27cd754593ca81b539a0a40c537579c4aeb4cfa0e3a0dd9c5dab92c1c839a5b8baf7d02e80ed0f7ef8bf6d233d02e",
          "sha256": "3c44193c1b0326a182c1b5902b22cf9627acf17805a2611aa371707e2f5a1c1e",
          "sha1": "a8ced44897545beaffc5688c0e347bc6d83819d6",
          "md5": "ed98e7beea4380e4454cf96a77359d77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "com.reduxrobotics.frc",
          "module": "ReduxLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "swervelib",
          "module": "YAGSL-java",
          "version": {
            "requires": "2026.3.14"
          }
        },
        {
          "group": "org.dyn4j",
          "module": "dyn4j",
          "version": {
            "requires": "5.0.2"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2026.0.5"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photonlib-java",
          "version": {
            "requires": "v2026.3.2"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photontargeting-java",
          "version": {
            "requires": "v2026.3.2"
          }
        },
        {
          "group": "com.thethriftybot.frc",
          "module": "ThriftyLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "org.ironmaple",
          "module": "maplesim-java",
          "version": {
            "requires": "0.3.14"
          }
        },
        {
          "group": "com.studica.frc",
          "module": "Studica-java",
          "version": {
            "requires": "2026.0.0"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.2"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.36.0"
          }
        }
      ],
      "files": [
        {
          "name": "AdambotsLib-java-2026.3.17.jar",
          "url": "AdambotsLib-java-2026.3.17.jar",
          "size": 26848072,
          "sha512": "ed3841f284112ea3e344847a240b855585f27cd754593ca81b539a0a40c537579c4aeb4cfa0e3a0dd9c5dab92c1c839a5b8baf7d02e80ed0f7ef8bf6d233d02e",
          "sha256": "3c44193c1b0326a182c1b5902b22cf9627acf17805a2611aa371707e2f5a1c1e",
          "sha1": "a8ced44897545beaffc5688c0e347bc6d83819d6",
          "md5": "ed98e7beea4380e4454cf96a77359d77"
        }
      ]
    }
  ]
}
