{
  "formatVersion": "1.1",
  "component": {
    "group": "com.adambots.lib",
    "module": "AdambotsLib-java",
    "version": "2026.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AdambotsLib-java-2026.2.7.jar",
          "url": "AdambotsLib-java-2026.2.7.jar",
          "size": 27847371,
          "sha512": "c32a4ce451dd008cb89ae6247845e79bc9e6c9d4d338492c26739e315d541a75ef8252acd8afbb1111d4fcbe09a7986db5e62cca6ef1ef7a673601ded13afb15",
          "sha256": "9e8f957f8d8de2ae3057f62f420dee1f34b075b0d6b451212ce74680600c6710",
          "sha1": "14104df76ad279fc3efbed35d7a4ade850a21e1b",
          "md5": "2e9953655605f11c2620993c2015bc4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "com.reduxrobotics.frc",
          "module": "ReduxLib-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "swervelib",
          "module": "YAGSL-java",
          "version": {
            "requires": "2026.2.3.1"
          }
        },
        {
          "group": "org.dyn4j",
          "module": "dyn4j",
          "version": {
            "requires": "5.0.2"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2026.0.1"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photonlib-java",
          "version": {
            "requires": "v2025.3.1"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photontargeting-java",
          "version": {
            "requires": "v2025.3.1"
          }
        },
        {
          "group": "com.thethriftybot.frc",
          "module": "ThriftyLib-java",
          "version": {
            "requires": "2026.0.1"
          }
        },
        {
          "group": "org.ironmaple",
          "module": "maplesim-java",
          "version": {
            "requires": "0.3.14"
          }
        },
        {
          "group": "com.studica.frc",
          "module": "Studica-java",
          "version": {
            "requires": "2026.0.0"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.36.0"
          }
        }
      ],
      "files": [
        {
          "name": "AdambotsLib-java-2026.2.7.jar",
          "url": "AdambotsLib-java-2026.2.7.jar",
          "size": 27847371,
          "sha512": "c32a4ce451dd008cb89ae6247845e79bc9e6c9d4d338492c26739e315d541a75ef8252acd8afbb1111d4fcbe09a7986db5e62cca6ef1ef7a673601ded13afb15",
          "sha256": "9e8f957f8d8de2ae3057f62f420dee1f34b075b0d6b451212ce74680600c6710",
          "sha1": "14104df76ad279fc3efbed35d7a4ade850a21e1b",
          "md5": "2e9953655605f11c2620993c2015bc4d"
        }
      ]
    }
  ]
}
